name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Setup and install tools
      run: |
          go get -u github.com/golang/protobuf/protoc-gen-go

    - name: Build and test
      env:
          GOPROXY: https://proxy.golang.org,direct
      run: |
        PATH=$GOPATH/bin:$PATH make test
        PATH=$GOPATH/bin:$PATH make lint

# BEGIN __DO_NOT_INCLUDE__
    - name: Test templating
      env:
          GOPROXY: https://proxy.golang.org,direct
      run: |
        make test-template
# END __DO_NOT_INCLUDE__
